# Where things are
source              : .
destination         : ./_site
collections_dir     : .
plugins_dir         : _plugins
plugins:
  - jekyll-seo-tag
layouts_dir         : _layouts
data_dir            : _data
includes_dir        : _includes
collections:
  articles:
    output          : true
  events:
    output          : true
  jobs:
    output          : true
  links:
    output          : true
  members:
    output          : true
    people          : true
  workshops:
    output          : true
